### ISSUE TITLE
ColoredGlass out of bounds access when edges is 0

### ISSUE THREAD

**Issue by RareBreeds** [alexey-komarov/fruitsofkarma-vcvrack#8]
I was randomizing ColoredGlass with address sanitizer enabled and it failed.

It looks like it's possible for `edges` to be calculated as 0 in `drawParticle`, causing 0 length `xs` and `ys`  VLAs which is UB.

Build command: `make -j8 EXTRA_FLAGS=-fsanitize=address EXTRA_LDFLAGS=-fsanitize=address`

Revision: 50def34a4800528ec703ee86e36f62f02f65fe46

Address sanitizer log:
```
=================================================================
==3352==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x00020d3f5ec0 at pc 0x00000fd1171d bp 0x00020d3f5e50 sp 0x00020d3f5e48
READ of size 4 at 0x00020d3f5ec0 thread T0
    #0 0xfd1171c in ColoredGlassGlWidget::drawParticle(rack::widget::Widget::DrawArgs const&, TParticle*) ColoredGlass.cpp:260
    #1 0xfd10d5c in ColoredGlassGlWidget::drawLayer(rack::widget::Widget::DrawArgs const&, int) ColoredGlass.cpp:278
    #2 0x5ddbf0c in rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int) Widget.cpp:295
    #3 0x5c72bf7 in rack::app::ModuleWidget::drawLayer(rack::widget::Widget::DrawArgs const&, int) ModuleWidget.cpp:304
    #4 0x5ddbf0c in rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int) Widget.cpp:295
    #5 0x5ddbf0c in rack::widget::Widget::drawLayer(rack::widget::Widget::DrawArgs const&, int) Widget.cpp:295
    #6 0x5cb8678 in rack::app::RackWidget::draw(rack::widget::Widget::DrawArgs const&) RackWidget.cpp:147
    #7 0x5ddb32d in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) Widget.cpp:280
    #8 0x5ddce3f in rack::widget::ZoomWidget::draw(rack::widget::Widget::DrawArgs const&) ZoomWidget.cpp:54
    #9 0x5ddb32d in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) Widget.cpp:280
    #10 0x5ddb32d in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) Widget.cpp:280
    #11 0x5dbc124 in rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&) ScrollWidget.cpp:68
    #12 0x5ddb32d in rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&) Widget.cpp:280
    #13 0x5deff2e in rack::window::Window::step() Window.cpp:504
    #14 0x5dee9f3 in rack::window::Window::run() Window.cpp:409
    #15 0x4854a04 in main standalone.cpp:239
    #16 0x104aca10a  (<unknown module>)

Address 0x00020d3f5ec0 is located in stack of thread T0
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow ColoredGlass.cpp:260 in ColoredGlassGlWidget::drawParticle(rack::widget::Widget::DrawArgs const&, TParticle*)
Shadow bytes around the buggy address:
  0x100041a7eb80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7eb90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7eba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7ebb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7ebc0: 00 00 00 00 00 00 00 00 00 00 00 00 ca ca ca ca
=>0x100041a7ebd0: cb cb cb cb ca ca ca ca[cb]cb cb cb 00 00 00 00
  0x100041a7ebe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7ebf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7ec00: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 f3 f3 f3 f3
  0x100041a7ec10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100041a7ec20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3352==ABORTING
Abort trap: 6
```

Potential fix - return early if there are no edges to draw. Not sure if it's correct though as there is some `p->inverted` and `p->locked` state where the behavior might have changed.
```
diff --git a/src/ColoredGlass.cpp b/src/ColoredGlass.cpp
index e29d5bd..68d5468 100644
--- a/src/ColoredGlass.cpp
+++ b/src/ColoredGlass.cpp
@@ -221,10 +221,14 @@ struct ColoredGlassGlWidget : ModuleLightWidget {
                        module->Reset = false;
                }
 
+               int edges = Settings.edges + p->edges * Settings.edgesRand;
+               if (edges <= 0) {
+                       return;
+               }
+
                int x = p->x + halfsize + Settings.centerX - 7;
                int y = p->y + halfsize + Settings.centerY - 10;
                int radius = std::max(0, std::min(int(Settings.radius + p->radius * Settings.radiusRand), RADIUS_MAX));
-               int edges = Settings.edges + p->edges * Settings.edgesRand;
                float angle = Settings.rotate + p->angle * Settings.rotateRand;
 
                angle = angle / 180 * NVG_PI;
```

**Comment by alexey-komarov** [comment]
Thank for this reporting, really appreciate. I think your fix is fine, I will apply it soon.
